src/Controllers/AssistController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using AutoMate.Data;
using AutoMate.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Shared.Asp.UserNotice;
using Shared.Utils.Asp;
using Shared.Utils.Core;

namespace AutoMate.Controllers
{
    public class AssistController : BaseController
    {
        public AssistController(ApplicationDbContext aContext, AmCoreService aCoreService) : base(aContext)
        {
            this.aCoreService = aCoreService;
        }


        #region Views
        public IActionResult About() => View();
        #endregion

        
        #if DEBUG
        [HttpPost]
        public IActionResult ClearSession()
        {
            HttpContext.Session.Clear();

            // Notify user:
            aCoreService.UserNotices.Enqueue(new UserNotice("Cleared session.", "Session", "", NoticeType.eSuccess));

            return (Redirect("/"));
        }


        #region Views
        public IActionResult Debug() => View();
        #endregion
        #endif


        private AmCoreService aCoreService;
    }
}

src/Views/Assist/About.cshtml
@using System.Reflection
@using System.ComponentModel
@using System.Diagnostics

@{
    ViewData["Title"] = "About AutoMate";
}
@functions
{
    public void PrintValue(string sTitle, string sValue, bool bHyperlink = false)
    {
        if (!string.IsNullOrEmpty(sValue))
        {
            <div class="mb-2 row">
                <label for="Val1" class="col-sm-3 col-form-label"><strong>@sTitle:</strong></label>
                <div class="col-sm-9">
                    @if (bHyperlink)
                    {
                        <a href="@sValue" class="card-link form-control-plaintext" target="_blank">@sValue</a>
                    }
                    else
                    {
                        <input type="text" readonly class="form-control-plaintext" id="Val1" value="@sValue">
                    }
                </div>
            </div>
        }
    }
}

<div class="card" style="width: 38rem;">
    @{
        var _aAsmExec = Assembly.GetExecutingAssembly();
        var _aAsmExecName = _aAsmExec.GetName();
        var _fAsmExecInfo = FileVersionInfo.GetVersionInfo(_aAsmExec.Location);

        var _aAsmEntry = Assembly.GetEntryAssembly();
        var _aAsmEntryName = _aAsmEntry.GetName();
        var _fAsmEntryInfo = FileVersionInfo.GetVersionInfo(_aAsmEntry.Location);

        // Print title:
        if (_fAsmExecInfo != null)
        {
            <div class="card-header">
                <h4 class="card-title">@_fAsmExecInfo.ProductName</h4>
                <h6 class="card-subtitle mb-2 text-muted">@_fAsmExecInfo.Comments</h6>
            </div>
        }
        <div class="card-body">
            @{
                // Print details:
                if (_fAsmExecInfo != null)
                {
                    <h5>Details</h5>
                    PrintValue("Author", _fAsmExecInfo.CompanyName);
                    <br>
                }

                // Print version:
                if (_aAsmEntry != null)
                {
                    <h5>Version</h5>
                    PrintValue("Assembly", _aAsmEntryName.Version.ToString());
                    PrintValue("File", _fAsmEntryInfo.FileVersion);
                    
                    bool _bIsDebug = false;
                    #if DEBUG
                    _bIsDebug = true;
                    #endif
                    var _sClass = _bIsDebug ? "alert-warning" : "alert-secondary";
                    var _sEnv = _bIsDebug ? "Debug" : "Production";
                    <div class="alert @_sClass" role="alert">
                        <strong>Environment:</strong> @_sEnv
                    </div>
                    <br>
                }

                // Print project information:
                if (_aAsmEntry != null)
                {
                    <h5>Project</h5>
                    PrintValue("URL", _aAsmEntry.GetCustomAttribute<AssemblyMetadataAttribute>()?.Value, true);
                }
            }
        </div>
        <div class="card-footer">
            <a href="https://gitlab.com/Meisterzunge/automate/-/blob/master/LICENSE.txt" class="card-link" target="_blank">License</a>
            <a href="https://gitlab.com/Meisterzunge/automate/-/wikis" class="card-link" target="_blank">Wiki</a>
            <a href="https://gitlab.com/Meisterzunge/automate/-/issues" class="card-link" target="_blank">Issues</a>
            <a href="https://gitlab.com/Meisterzunge/automate/-/tree/master" class="card-link" target="_blank">Contribute</a>
        </div>
    }
</div>

src/Views/Assist/Debug.cshtml
@{
    ViewData["Title"] = "Debug";
}


<div>DEBUG</div>
<p>
  <form asp-area="" asp-controller="Assist" asp-action="ClearSession" method="post">
      <button type="submit" class="btn btn-secondary">Clear session</button>
  </form>
</p>